# doc here https://docs.confluent.io/current/installation/docker/docs/config-reference.html                                           
version: "2.1"
networks:
  internal:

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:${CONFLUENT_VERSION:-4.1.0}
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - KAFKA_HEAP_OPTS=-Xmx128M -Xms128M
    networks:
      - internal

  broker:
    image: confluentinc/cp-kafka:${CONFLUENT_VERSION:-4.1.0}
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_SERVER:-kafka}:9092
      - KAFKA_HEAP_OPTS=-Xmx512M -Xms512M
    extra_hosts:
      - "${KAFKA_SERVER:-kafka}:${KAFKA_HOSTIP:-172.17.0.1}"
    networks:
      - internal

  registry:
    image: confluentinc/cp-schema-registry:${CONFLUENT_VERSION:-4.1.0}
    hostname: registry
    container_name: registry
    depends_on:
      - broker
      - zookeeper
    links:
      - broker:${KAFKA_SERVER:-kafka}
    ports:
      - 8081:8081
    environment:
      - SCHEMA_REGISTRY_HOST_NAME=${KAFKA_SERVER:-kafka}
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
      - SCHEMA_REGISTRY_LISTENERS=http://registry:8081
      - SCHEMA_REGISTRY_HEAP_OPTS=-Xmx256M
    networks:
      - internal
