name: build
on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build test container image
        run: docker build --pull -t docker.pkg.github.com/${{ github.repository }}:test -f Dockerfile.test .
      - name: test
        run:  docker run -t --rm -v $(pwd):/work -w /work docker.pkg.github.com/${{ github.repository }}:test  run make createtopic test
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}:latest


