name: build
on:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build test container image
        run: docker build --pull -t kafkacli_ci -f Dockerfile.test .
      - name: test
        run:  docker run -t --rm -v $(pwd):/work -w /work kafkacli_ci run make createtopic test
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: hbraux
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            hbraux/kafkacli:latest
            hbraux/kafkacli:0.1.4
